'use client';

import React, { useState, useEffect } from 'react';
import {
  CMSMarketingCampaign,
  CMSPixelConfig,
  AbandonedCartData,
  MarketingChannel,
} from '@/src/types';
import { cmsService } from '@/src/services/cmsService';
import { useCMSContext } from '@/src/context/CMSContext';
import { getCurrencySymbol } from '@/src/lib/currency';
import { usePlanAccess } from '@/src/hooks/usePlanAccess';
import { LockedFeatureGuard } from '@/src/components/cms/LockedFeatureGuard';
import {
  Megaphone,
  Mail,
  MessageSquare,
  MessageCircle,
  Bell,
  ShoppingCart,
  Tag,
  Ticket,
  TrendingUp,
  Target,
  BarChart2,
  Copy,
  Check,
  Plus,
  Send,
  Eye,
  Trash2,
  Edit2,
  CheckCircle2,
  AlertCircle,
  X,
  RefreshCw,
  Share2,
  Zap,
  DollarSign,
  Users,
  ShieldCheck,
  ExternalLink,
  Percent,
  Info,
  HelpCircle,
  BookOpen,
  Key,
  Sparkles,
} from 'lucide-react';

interface PixelGuide {
  id: string;
  name: string;
  category: string;
  badgeBg: string;
  badgeText: string;
  summary: string;
  whatItDoes: string[];
  howToUse: string[];
  howToGetAccessKey: {
    steps: string[];
    formatExample: string;
    portalName: string;
    portalUrl: string;
  };
}

const PIXEL_HELP_GUIDES: Record<string, PixelGuide> = {
  ga4: {
    id: 'ga4',
    name: 'Google Analytics 4 (GA4)',
    category: 'Traffic & Funnel Analytics',
    badgeBg: 'bg-amber-100 text-amber-800 dark:bg-amber-950/60 dark:text-amber-300 border-amber-200 dark:border-amber-800',
    badgeText: 'Google Web Analytics',
    summary: 'Google Analytics 4 measures visitor volume, user journeys, acquisition channels, and shopping funnels across your online store.',
    whatItDoes: [
      'Tracks total visits, bounce rates, active sessions, and shopper locations.',
      'Identifies whether customers find your store via Organic Search, Google Ads, Direct links, or Social channels.',
      'Measures where shoppers drop off in the checkout process to improve conversion rates.',
    ],
    howToUse: [
      'Enter your GA4 Measurement ID in the input box (starts with "G-").',
      'Click the toggle button to switch it to "Enabled".',
      'Click "Save Pixel Configurations" at the bottom of the page.',
      'The storefront will automatically initialize gtag.js and send PageView, view_item, add_to_cart, begin_checkout, and purchase events with zero code changes needed.',
    ],
    howToGetAccessKey: {
      steps: [
        'Open Google Analytics (analytics.google.com) and log in with your Google Account.',
        'Click the Admin gear icon in the bottom-left corner of the dashboard.',
        'Under the Property column, click Data Streams, then select the Web tab.',
        'Click on your store web stream (or create one by clicking "Add Stream" > "Web").',
        'In the Stream Details panel, copy the Measurement ID (e.g., G-XXXXXXXXXX).',
      ],
      formatExample: 'G-XXXXXXXXXX (e.g. G-9B87F4X2K1)',
      portalName: 'Open Google Analytics Admin',
      portalUrl: 'https://analytics.google.com',
    },
  },
  meta: {
    id: 'meta',
    name: 'Meta Pixel (Facebook & Instagram)',
    category: 'Ad Retargeting & Social Ads',
    badgeBg: 'bg-blue-100 text-blue-800 dark:bg-blue-950/60 dark:text-blue-300 border-blue-200 dark:border-blue-800',
    badgeText: 'Meta Advertising',
    summary: 'The Meta Pixel connects your store with Facebook & Instagram Ads Manager to track ad conversions, optimize campaigns, and retarget shoppers.',
    whatItDoes: [
      'Tracks purchases and return on ad spend (ROAS) generated by Facebook & Instagram ads.',
      'Builds Lookalike Audiences to find new customers similar to your existing buyers.',
      'Enables Dynamic Product Retargeting ads showing exact viewed products to shoppers who abandoned their cart.',
    ],
    howToUse: [
      'Enter your numeric Meta Pixel / Dataset ID in the input box.',
      'Toggle the status to "Enabled" and save.',
      'The storefront loads fbevents.js and automatically tracks PageView, ViewContent, AddToCart, InitiateCheckout, and Purchase.',
    ],
    howToGetAccessKey: {
      steps: [
        'Visit Meta Events Manager (business.facebook.com/events_manager).',
        'Log in with your Meta Business / Facebook Account.',
        'In the left sidebar, click Data Sources and select your Pixel / Dataset.',
        'Click on the Settings tab in the top navigation.',
        'Find Dataset ID / Pixel ID (a 15–16 digit number) and click to copy.',
      ],
      formatExample: '15 to 16 digit number (e.g. 182938475610293)',
      portalName: 'Open Meta Events Manager',
      portalUrl: 'https://business.facebook.com/events_manager',
    },
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok Ads Pixel',
    category: 'Short-Video Ads & Commerce',
    badgeBg: 'bg-rose-100 text-rose-800 dark:bg-rose-950/60 dark:text-rose-300 border-rose-200 dark:border-rose-800',
    badgeText: 'TikTok for Business',
    summary: 'Track conversions from viral TikTok videos and paid TikTok Ads to maximize sales from mobile shoppers.',
    whatItDoes: [
      'Measures store sales driven by TikTok video campaigns and influencer sponsorships.',
      'Optimizes TikTok bidding algorithms toward users most likely to make a purchase.',
      'Creates custom audience segments based on storefront interactions.',
    ],
    howToUse: [
      'Enter your TikTok Pixel ID code in the input field.',
      'Switch the status to "Enabled" and click Save.',
      'Storefront injects ttq.js and dispatches PageView, ViewContent, AddToCart, InitiateCheckout, and PlaceAnOrder.',
    ],
    howToGetAccessKey: {
      steps: [
        'Log in to TikTok Ads Manager (ads.tiktok.com).',
        'In the top menu, navigate to Tools > Events (or Assets > Events).',
        'Under Web Events, click Manage.',
        'Select your Pixel Name to open its details page.',
        'Under the Settings tab, copy your Pixel ID code.',
      ],
      formatExample: 'Alphanumeric code (e.g. C1234567890ABCDEFGH)',
      portalName: 'Open TikTok Ads Manager',
      portalUrl: 'https://ads.tiktok.com',
    },
  },
  pinterest: {
    id: 'pinterest',
    name: 'Pinterest Tag',
    category: 'Visual Commerce & Product Pins',
    badgeBg: 'bg-red-100 text-red-800 dark:bg-red-950/60 dark:text-red-300 border-red-200 dark:border-red-800',
    badgeText: 'Pinterest Business',
    summary: 'Track conversions from Promoted Pins and Pinterest Shopping catalog campaigns.',
    whatItDoes: [
      'Measures sales originating from Pinterest product boards and promoted visual pins.',
      'Identifies high-intent shoppers searching for style, decor, and fashion inspiration.',
      'Enables conversion-focused bidding on Pinterest Ads.',
    ],
    howToUse: [
      'Paste your numeric Pinterest Tag ID in the input box.',
      'Switch to "Enabled" and click Save.',
      'The storefront injects pintrk.js and triggers pagevisit, PageVisit (PDP), AddToCart, and Checkout.',
    ],
    howToGetAccessKey: {
      steps: [
        'Log in to Pinterest Business Hub (ads.pinterest.com).',
        'Click Ads in the top menu and select Conversions / Tag Manager.',
        'Locate your unique Tag ID next to your tag name.',
        'Copy the numeric Tag ID.',
      ],
      formatExample: '13-digit number (e.g. 2612345678901)',
      portalName: 'Open Pinterest Tag Manager',
      portalUrl: 'https://ads.pinterest.com',
    },
  },
  adobe: {
    id: 'adobe',
    name: 'Adobe Analytics (Launch / Experience Platform)',
    category: 'Enterprise Customer Data Platform',
    badgeBg: 'bg-purple-100 text-purple-800 dark:bg-purple-950/60 dark:text-purple-300 border-purple-200 dark:border-purple-800',
    badgeText: 'Adobe Experience Cloud',
    summary: 'Enterprise-grade real-time web analytics, data governance, and customer journey orchestration via Adobe Experience Platform (AEP).',
    whatItDoes: [
      'Integrates storefront interactions with Adobe Experience Cloud and Adobe Target for personalization.',
      'Maintains a standardized client-side data layer (window.adobeDataLayer).',
      'Provides multi-touch marketing attribution and advanced segment discovery.',
    ],
    howToUse: [
      'Paste your Adobe Launch Header Script URL (assets.adobedtm.com) in the field.',
      'Toggle to "Enabled" and save.',
      'Storefront injects the Adobe Launch script into <head> and dispatches events to window.adobeDataLayer and window._satellite.',
    ],
    howToGetAccessKey: {
      steps: [
        'Sign in to Adobe Experience Cloud (experience.adobe.com).',
        'Open Data Collection (formerly Adobe Launch / Tags).',
        'Select your Web Property and click the Environments tab.',
        'Click the Install icon next to your Production (or Staging) environment.',
        'Copy the script tag source URL (e.g. https://assets.adobedtm.com/launch-ENxxxxxxxxxxxx-production.min.js).',
      ],
      formatExample: 'https://assets.adobedtm.com/launch-ENxxxxxxxxxxxx-production.min.js',
      portalName: 'Open Adobe Data Collection',
      portalUrl: 'https://experience.adobe.com',
    },
  },
  clevertap: {
    id: 'clevertap',
    name: 'CleverTap Customer Engagement',
    category: 'Lifecycle & Retention Automation',
    badgeBg: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
    badgeText: 'Customer Data Platform',
    summary: 'Real-time behavioral tracking, personalized web push notifications, and automated cart abandonment recovery campaigns.',
    whatItDoes: [
      'Tracks user actions in real-time to trigger automated cart recovery emails and WhatsApp messages.',
      'Builds dynamic customer cohorts based on shopping frequency and purchase value.',
      'Enables personalized on-site banners and browser push notifications.',
    ],
    howToUse: [
      'Enter your CleverTap Account / Project ID and optional Passcode.',
      'Select your Region Cluster (e.g., in1 for India, us1 for United States, sg1, eu1).',
      'Toggle to "Enabled" and save.',
      'The storefront initializes clevertap.min.js and sends Page Viewed, Product Viewed, Added to Cart, Checkout Started, and Charged events.',
    ],
    howToGetAccessKey: {
      steps: [
        'Log in to your CleverTap Dashboard (clevertap.com).',
        'Click Settings (gear icon in bottom left) > Account.',
        'Under Project Credentials, copy the Project ID (Account ID) and optional Passcode.',
        'Check your dashboard URL for your Region Cluster (e.g., in1.dashboard.clevertap.com means region is "in1").',
      ],
      formatExample: 'Account ID: W9R-444-TEST | Region: in1, us1, sg1, eu1',
      portalName: 'Open CleverTap Dashboard',
      portalUrl: 'https://clevertap.com',
    },
  },
};

export const MarketingStudio: React.FC = () => {
  const { isStarter } = usePlanAccess();
  let currencySymbol = '₹';
  try {
    const cmsCtx = useCMSContext();
    currencySymbol = cmsCtx.currencySymbol || '₹';
  } catch {
    const session = cmsService.getMerchantSession();
    currencySymbol = getCurrencySymbol(session?.store?.currency || 'INR');
  }

  const [campaigns, setCampaigns] = useState<CMSMarketingCampaign[]>([]);
  const [pixelConfig, setPixelConfig] = useState<CMSPixelConfig>({});
  const [abandonedCarts, setAbandonedCarts] = useState<AbandonedCartData[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<
    'CAMPAIGNS' | 'EMAIL' | 'SMS' | 'WHATSAPP' | 'PUSH' | 'ABANDONED_CART' | 'PIXELS' | 'UTM'
  >('CAMPAIGNS');
  const [toastMessage, setToastMessage] = useState<{
    text: string;
    type: 'success' | 'error';
  } | null>(null);

  const [activePixelGuide, setActivePixelGuide] = useState<PixelGuide | null>(null);

  // Campaign Modal
  const [isCampaignModalOpen, setIsCampaignModalOpen] = useState(false);
  const [campaignForm, setCampaignForm] = useState<{
    title: string;
    channel: MarketingChannel;
    targetSegment: string;
    subject: string;
    body: string;
  }>({
    title: '',
    channel: 'EMAIL',
    targetSegment: 'All Subscribers',
    subject: '',
    body: '',
  });

  // UTM Builder State
  const [utmUrl, setUtmUrl] = useState('');
  const [utmSource, setUtmSource] = useState('');
  const [utmMedium, setUtmMedium] = useState('');
  const [utmCampaign, setUtmCampaign] = useState('');
  const [utmTerm, setUtmTerm] = useState('');
  const [utmContent, setUtmContent] = useState('');
  const [copiedUtm, setCopiedUtm] = useState(false);

  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    setIsLoading(true);
    try {
      const [campData, pixData, cartData] = await Promise.all([
        cmsService.getMarketingCampaigns(),
        cmsService.getPixelConfig(),
        cmsService.getAbandonedCarts(),
      ]);
      setCampaigns(campData);
      setPixelConfig(pixData);
      setAbandonedCarts(cartData);
    } catch (err) {
      console.error('Failed to load marketing data:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const showToast = (text: string, type: 'success' | 'error' = 'success') => {
    setToastMessage({ text, type });
    setTimeout(() => setToastMessage(null), 4000);
  };

  // CAMPAIGN CREATION
  const handleOpenCreateCampaign = (channel: MarketingChannel = 'EMAIL') => {
    setCampaignForm({
      title: '',
      channel,
      targetSegment: 'All Customers',
      subject: channel === 'EMAIL' ? '🔥 Special Offer Just for You!' : 'New Update',
      body: 'Explore our latest collections and enjoy exclusive discounts on your order today!',
    });
    setIsCampaignModalOpen(true);
  };

  const handleSaveCampaign = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);
    try {
      const created = await cmsService.createMarketingCampaign({
        title: campaignForm.title,
        channel: campaignForm.channel,
        targetSegment: campaignForm.targetSegment,
        subject: campaignForm.subject,
        body: campaignForm.body,
        status: 'SENT',
      });

      showToast(`Marketing broadcast "${created.title}" sent successfully!`, 'success');
      setIsCampaignModalOpen(false);
      await loadData();
    } catch (err: any) {
      showToast(err.message || 'Failed to send broadcast.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteCampaign = async (id: string) => {
    try {
      setIsSaving(true);
      await cmsService.deleteMarketingCampaign(id);
      showToast('Campaign deleted.', 'success');
      await loadData();
    } catch (err: any) {
      showToast(err.message || 'Failed to delete campaign.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // CART RECOVERY
  const handleSendRecovery = async (id: string) => {
    try {
      setIsSaving(true);
      const updated = await cmsService.sendCartRecoveryEmail(id);
      showToast(`Cart recovery email sent to ${updated.customerEmail}!`, 'success');
      await loadData();
    } catch (err: any) {
      showToast(err.message || 'Failed to send recovery email.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // PIXELS UPDATE
  const handleSavePixels = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);
    try {
      await cmsService.updatePixelConfig(pixelConfig);
      showToast('Tracking pixels configuration updated!', 'success');
      await loadData();
    } catch (err: any) {
      showToast(err.message || 'Failed to update pixels.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // UTM GENERATOR COMPUTED
  const generatedUtmUrl = utmUrl
    ? `${utmUrl}${utmUrl.includes('?') ? '&' : '?'}utm_source=${encodeURIComponent(utmSource || 'source')}&utm_medium=${encodeURIComponent(utmMedium || 'medium')}&utm_campaign=${encodeURIComponent(utmCampaign || 'campaign')}${utmTerm ? `&utm_term=${encodeURIComponent(utmTerm)}` : ''}${utmContent ? `&utm_content=${encodeURIComponent(utmContent)}` : ''}`
    : '';

  const handleCopyUtm = () => {
    navigator.clipboard.writeText(generatedUtmUrl);
    setCopiedUtm(true);
    setTimeout(() => setCopiedUtm(false), 3000);
    showToast('UTM Tracking URL copied to clipboard!', 'success');
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[350px] gap-3">
        <div className="w-10 h-10 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin" />
        <span className="text-xs font-bold text-slate-500 animate-pulse">
          Loading Marketing & Growth Studio...
        </span>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-16">
      {/* Toast Notification */}
      {toastMessage && (
        <div
          className={`fixed bottom-6 right-6 z-50 flex items-center gap-3 px-5 py-3.5 rounded-2xl shadow-xl border backdrop-blur-md transition-all animate-in slide-in-from-bottom-5 ${
            toastMessage.type === 'success'
              ? 'bg-emerald-900/90 text-white border-emerald-700'
              : 'bg-rose-900/90 text-white border-rose-700'
          }`}
        >
          {toastMessage.type === 'success' ? (
            <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
          ) : (
            <AlertCircle className="w-5 h-5 text-rose-400 shrink-0" />
          )}
          <span className="text-xs font-bold">{toastMessage.text}</span>
        </div>
      )}

      {/* Header Banner */}
      <div className="p-6 sm:p-8 rounded-3xl bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white shadow-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-indigo-500/10 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none" />
        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <span className="px-3 py-1 rounded-full bg-indigo-500/20 text-indigo-300 font-extrabold text-[11px] uppercase tracking-wider border border-indigo-500/30">
                Multi-Channel Growth Suite
              </span>
              <span className="px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 text-[10px] font-bold border border-emerald-500/30">
                ${campaigns.reduce((acc, c) => acc + c.revenueTotal, 0).toFixed(2)} Campaign Revenue
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-white flex items-center gap-3">
              <Megaphone className="w-8 h-8 text-indigo-400" />
              <span>Marketing & Growth Studio</span>
            </h1>
            <p className="text-xs sm:text-sm text-slate-300 max-w-2xl">
              Execute Email, SMS, WhatsApp Business, & Web Push broadcasts, recover lost abandoned
              cart revenue, build UTM tracking links, and configure Google Analytics & Meta Pixels.
            </p>
          </div>

          <button
            type="button"
            onClick={() => handleOpenCreateCampaign('EMAIL')}
            className="px-5 py-3 rounded-2xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-extrabold shadow-lg shadow-indigo-600/30 flex items-center gap-2 transition-all shrink-0"
          >
            <Plus className="w-4 h-4" />
            <span>Create Campaign Broadcast</span>
          </button>
        </div>
      </div>

      {/* KPI METRICS OVERVIEW */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-5 rounded-3xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-xs flex items-center justify-between">
          <div>
            <span className="text-[11px] font-extrabold text-slate-400 uppercase tracking-wider block">
              Total Campaign Reach
            </span>
            <span className="text-2xl font-black text-slate-900 dark:text-foreground block">
              {campaigns.reduce((acc, c) => acc + c.sentCount, 0).toLocaleString()}
            </span>
          </div>
          <Users className="w-8 h-8 text-indigo-600" />
        </div>

        <div className="p-5 rounded-3xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-xs flex items-center justify-between">
          <div>
            <span className="text-[11px] font-extrabold text-slate-400 uppercase tracking-wider block">
              Total Clicks & Engagement
            </span>
            <span className="text-2xl font-black text-indigo-600 block">
              {campaigns.reduce((acc, c) => acc + c.clickCount, 0).toLocaleString()}
            </span>
          </div>
          <TrendingUp className="w-8 h-8 text-indigo-500" />
        </div>

        <div className="p-5 rounded-3xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-xs flex items-center justify-between">
          <div>
            <span className="text-[11px] font-extrabold text-slate-400 uppercase tracking-wider block">
              Conversion Orders
            </span>
            <span className="text-2xl font-black text-emerald-600 block">
              {campaigns.reduce((acc, c) => acc + c.conversionCount, 0)} Orders
            </span>
          </div>
          <CheckCircle2 className="w-8 h-8 text-emerald-500" />
        </div>

        <div className="p-5 rounded-3xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-xs flex items-center justify-between">
          <div>
            <span className="text-[11px] font-extrabold text-slate-400 uppercase tracking-wider block">
              Cart Recovery Revenue
            </span>
            <span className="text-2xl font-black text-amber-500 block">
              $
              {abandonedCarts
                .filter((c) => c.status === 'RECOVERED')
                .reduce((acc, c) => acc + (c.cartSubtotal || 0), 0)
                .toFixed(2)}
            </span>
          </div>
          <ShoppingCart className="w-8 h-8 text-amber-400" />
        </div>
      </div>

      {/* 8 SUB-NAVIGATION TABS */}
      <div className="p-4 rounded-3xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-sm">
        <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-none">
          {[
            { id: 'CAMPAIGNS', label: 'All Campaigns', icon: Megaphone },
            { id: 'EMAIL', label: 'Email Marketing', icon: Mail },
            { id: 'SMS', label: 'SMS Broadcasts', icon: MessageSquare },
            { id: 'WHATSAPP', label: 'WhatsApp Business', icon: MessageCircle },
            { id: 'PUSH', label: 'Push Notifications', icon: Bell },
            { id: 'ABANDONED_CART', label: 'Abandoned Carts', icon: ShoppingCart },
            { id: 'PIXELS', label: 'Pixels & GA4', icon: Target },
            { id: 'UTM', label: 'UTM URL Builder', icon: Share2 },
          ].map((tab) => {
            const isActive = activeTab === tab.id;
            const IconC = tab.icon;
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id as any)}
                className={`px-4 py-2.5 rounded-2xl text-xs font-extrabold transition-all flex items-center gap-2 shrink-0 ${
                  isActive
                    ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900 shadow-md'
                    : 'bg-slate-100 dark:bg-accent text-slate-700 dark:text-slate-300 hover:bg-slate-200'
                }`}
              >
                <IconC className="w-3.5 h-3.5" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* TAB CONTENT AREAS */}

      {/* 1. CAMPAIGNS / EMAIL / SMS / WHATSAPP / PUSH TABS */}
      {['CAMPAIGNS', 'EMAIL', 'SMS', 'WHATSAPP', 'PUSH'].includes(activeTab) && (
        <div className="rounded-3xl border border-slate-200/80 dark:border-border bg-white dark:bg-card shadow-sm overflow-hidden space-y-4 p-6">
          <div className="flex items-center justify-between">
            <h3 className="font-black text-base text-slate-900 dark:text-foreground flex items-center gap-2">
              <Megaphone className="w-5 h-5 text-indigo-600" />
              <span>Marketing Campaign Broadcasts</span>
            </h3>

            <div className="flex items-center gap-2.5">
              <a
                href="/email-templates"
                className="px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-indigo-600 dark:text-indigo-400 text-xs font-extrabold flex items-center gap-1.5 border border-indigo-200 dark:border-indigo-900/50 transition-all"
              >
                <Mail className="w-3.5 h-3.5" />
                <span>Email Template Builder</span>
              </a>

              <button
                type="button"
                onClick={() =>
                  handleOpenCreateCampaign(activeTab === 'CAMPAIGNS' ? 'EMAIL' : (activeTab as any))
                }
                className="px-4 py-2 rounded-xl bg-indigo-600 text-white text-xs font-extrabold flex items-center gap-1.5 shadow-md shadow-indigo-600/30"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>New {activeTab === 'CAMPAIGNS' ? 'Broadcast' : activeTab}</span>
              </button>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="bg-slate-50 dark:bg-accent border-b border-slate-200/80 dark:border-border text-slate-500 font-extrabold uppercase text-[10px] tracking-wider">
                  <th className="py-4 px-6">Campaign Title</th>
                  <th className="py-4 px-6">Channel</th>
                  <th className="py-4 px-6">Target Audience</th>
                  <th className="py-4 px-6">Sent Reach</th>
                  <th className="py-4 px-6">Clicks & CTR</th>
                  <th className="py-4 px-6">Revenue ({currencySymbol})</th>
                  <th className="py-4 px-6 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-border font-medium text-slate-800 dark:text-slate-200">
                {(() => {
                  const filtered = campaigns.filter((c) =>
                    activeTab === 'CAMPAIGNS' ? true : c.channel === activeTab,
                  );
                  if (filtered.length === 0) {
                    return (
                      <tr>
                        <td colSpan={7} className="text-center py-16 text-slate-400">
                          <Megaphone className="w-8 h-8 text-slate-300 dark:text-slate-600 mx-auto mb-2" />
                          <span className="block text-slate-600 dark:text-slate-300 font-bold text-sm">
                            No campaigns found
                          </span>
                          <span className="text-xs text-slate-400 font-normal">
                            Create your first broadcast to start engaging your audience.
                          </span>
                        </td>
                      </tr>
                    );
                  }
                  return filtered.map((c) => (
                    <tr
                      key={c.id}
                      className="hover:bg-slate-50/80 dark:hover:bg-accent/50 transition-colors"
                    >
                      <td className="py-4 px-6">
                        <div className="font-extrabold text-sm text-slate-900 dark:text-foreground">
                          {c.title}
                        </div>
                        <div className="text-[11px] text-slate-400 italic">{c.subject}</div>
                      </td>
                      <td className="py-4 px-6">
                        <span className="px-2.5 py-1 rounded-full bg-slate-100 dark:bg-accent font-black text-[10px] uppercase text-indigo-600 dark:text-indigo-400">
                          {c.channel}
                        </span>
                      </td>
                      <td className="py-4 px-6 font-semibold">{c.targetSegment}</td>
                      <td className="py-4 px-6 font-bold">{c.sentCount.toLocaleString()} Sent</td>
                      <td className="py-4 px-6">
                        <span className="font-black text-slate-900 dark:text-foreground">
                          {c.clickCount} Clicks
                        </span>
                        <span className="text-[10px] text-slate-400 block font-mono">
                          {((c.clickCount / (c.sentCount || 1)) * 100).toFixed(1)}% CTR
                        </span>
                      </td>
                      <td className="py-4 px-6 font-black text-sm text-emerald-600">
                        {currencySymbol}
                        {c.revenueTotal.toFixed(2)}
                      </td>
                      <td className="py-4 px-6 text-right space-x-2">
                        <button
                          type="button"
                          onClick={() => handleDeleteCampaign(c.id)}
                          className="p-1.5 rounded-xl bg-slate-100 dark:bg-accent text-rose-500 hover:bg-rose-50"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </td>
                    </tr>
                  ));
                })()}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* 2. ABANDONED CART RECOVERY TAB */}
      {activeTab === 'ABANDONED_CART' &&
        (isStarter ? (
          <LockedFeatureGuard
            title="Automated Abandoned Cart Recovery"
            description="Recover up to 25% of lost revenue automatically by sending smart 1-click cart recovery emails with discount vouchers to shoppers who dropped off."
            requiredPlan="GROWTH"
            features={[
              'Automated 1-hour & 24-hour Cart Recovery Triggers',
              'Dynamic Auto-Generated Discount Vouchers (e.g. 10% OFF)',
              '1-Click Direct Pre-filled Checkout Links',
              'Real-Time Cart Value & Drop-off Analytics',
            ]}
          />
        ) : (
          <div className="p-6 rounded-3xl border border-slate-200/80 dark:border-border bg-white dark:bg-card shadow-sm space-y-4">
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <h3 className="font-black text-base text-slate-900 dark:text-foreground flex items-center gap-2">
                  <ShoppingCart className="w-5 h-5 text-amber-500" />
                  <span>Abandoned Checkout Recovery Engine</span>
                </h3>
                <p className="text-xs text-slate-500">
                  Automatically recover lost revenue by dispatching 1-click cart recovery emails
                  with promo vouchers.
                </p>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-50 dark:bg-accent border-b border-slate-200/80 dark:border-border text-slate-500 font-extrabold uppercase text-[10px] tracking-wider">
                    <th className="py-4 px-6">Customer</th>
                    <th className="py-4 px-6">Items Count</th>
                    <th className="py-4 px-6">Cart Subtotal</th>
                    <th className="py-4 px-6">Abandoned Time</th>
                    <th className="py-4 px-6">Recovery Voucher</th>
                    <th className="py-4 px-6 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-border font-medium text-slate-800 dark:text-slate-200">
                  {abandonedCarts.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="text-center py-16 text-slate-400">
                        <ShoppingCart className="w-8 h-8 text-slate-300 dark:text-slate-600 mx-auto mb-2" />
                        <span className="block text-slate-600 dark:text-slate-300 font-bold text-sm">
                          No abandoned checkouts
                        </span>
                        <span className="text-xs text-slate-400 font-normal">
                          Abandoned customer carts will automatically appear here once shoppers
                          leave checkout.
                        </span>
                      </td>
                    </tr>
                  ) : (
                    abandonedCarts.map((ac) => (
                      <tr
                        key={ac.id}
                        className="hover:bg-slate-50/80 dark:hover:bg-accent/50 transition-colors"
                      >
                        <td className="py-4 px-6">
                          <div className="font-extrabold text-slate-900 dark:text-foreground">
                            {ac.customerName}
                          </div>
                          <div className="text-[11px] font-mono text-indigo-600">
                            {ac.customerEmail}
                          </div>
                        </td>
                        <td className="py-4 px-6 font-bold">{ac.itemsCount} Items</td>
                        <td className="py-4 px-6 font-black text-sm text-slate-900 dark:text-foreground">
                          {currencySymbol}
                          {ac.cartSubtotal.toFixed(2)}
                        </td>
                        <td className="py-4 px-6 text-slate-500 font-semibold">{ac.abandonedAt}</td>
                        <td className="py-4 px-6">
                          <span className="px-2.5 py-1 rounded-xl bg-amber-100 font-mono font-black text-[10px] text-amber-800">
                            {ac.recoveryDiscountCode || 'RECOVER10'}
                          </span>
                        </td>
                        <td className="py-4 px-6 text-right">
                          {ac.status === 'EMAIL_SENT' ? (
                            <span className="px-3 py-1.5 rounded-xl bg-emerald-50 text-emerald-700 text-[11px] font-extrabold inline-flex items-center gap-1">
                              <CheckCircle2 className="w-3.5 h-3.5" />
                              <span>Recovery Email Sent</span>
                            </span>
                          ) : (
                            <button
                              type="button"
                              onClick={() => handleSendRecovery(ac.id)}
                              className="px-3.5 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-extrabold text-[11px] inline-flex items-center gap-1 shadow-sm"
                            >
                              <Send className="w-3.5 h-3.5" />
                              <span>Send Recovery Email</span>
                            </button>
                          )}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        ))}

      {/* 3. TRACKING PIXELS & GA4 TAB */}
      {activeTab === 'PIXELS' && (
        <form
          onSubmit={handleSavePixels}
          className="p-6 rounded-3xl border border-slate-200/80 dark:border-border bg-white dark:bg-card shadow-sm space-y-6"
        >
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b pb-4">
            <div className="space-y-1">
              <h3 className="font-black text-lg text-slate-900 dark:text-foreground flex items-center gap-2">
                <Target className="w-5 h-5 text-indigo-600" />
                <span>Tracking Pixels & Analytics Integration</span>
              </h3>
              <p className="text-xs text-slate-500">
                Inject Google Analytics 4, Meta Pixel, TikTok Pixel, Pinterest Tag, Adobe Launch, and
                CleverTap automatically into your storefront.
              </p>
            </div>
            <button
              type="button"
              onClick={() => setActivePixelGuide(PIXEL_HELP_GUIDES.ga4)}
              className="self-start sm:self-auto px-4 py-2 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 hover:bg-indigo-100 dark:hover:bg-indigo-900/60 text-indigo-600 dark:text-indigo-400 text-xs font-bold border border-indigo-200 dark:border-indigo-800 flex items-center gap-2 transition shadow-sm"
            >
              <BookOpen className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
              <span>Pixel & Key Setup Guide</span>
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* GA4 */}
            <div className="p-5 rounded-2xl bg-slate-50 dark:bg-accent/40 border border-slate-200 dark:border-border space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="font-black text-sm text-slate-900 dark:text-foreground">
                    Google Analytics 4 (GA4)
                  </span>
                  <button
                    type="button"
                    onClick={() => setActivePixelGuide(PIXEL_HELP_GUIDES.ga4)}
                    className="p-1 rounded-full text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 dark:hover:bg-indigo-950/50 transition cursor-pointer"
                    title="Learn what GA4 does and how to get your Measurement ID"
                  >
                    <Info className="w-4 h-4 text-indigo-500" />
                  </button>
                </div>
                <button
                  type="button"
                  onClick={() =>
                    setPixelConfig({ ...pixelConfig, isGa4Active: !pixelConfig.isGa4Active })
                  }
                  className={`px-3 py-1 rounded-full text-xs font-black transition ${
                    pixelConfig.isGa4Active
                      ? 'bg-emerald-600 text-white shadow-sm'
                      : 'bg-slate-200 text-slate-600'
                  }`}
                >
                  {pixelConfig.isGa4Active ? 'Enabled' : 'Disabled'}
                </button>
              </div>
              <input
                type="text"
                value={pixelConfig.ga4MeasurementId || ''}
                onChange={(e) =>
                  setPixelConfig({ ...pixelConfig, ga4MeasurementId: e.target.value })
                }
                placeholder="e.g. G-X987654321"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-white text-xs font-mono font-bold text-indigo-600"
              />
            </div>

            {/* Meta Pixel */}
            <div className="p-5 rounded-2xl bg-slate-50 dark:bg-accent/40 border border-slate-200 dark:border-border space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="font-black text-sm text-slate-900 dark:text-foreground">
                    Meta Pixel (Facebook & Instagram)
                  </span>
                  <button
                    type="button"
                    onClick={() => setActivePixelGuide(PIXEL_HELP_GUIDES.meta)}
                    className="p-1 rounded-full text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 dark:hover:bg-indigo-950/50 transition cursor-pointer"
                    title="Learn what Meta Pixel does and how to get your Pixel ID"
                  >
                    <Info className="w-4 h-4 text-indigo-500" />
                  </button>
                </div>
                <button
                  type="button"
                  onClick={() =>
                    setPixelConfig({ ...pixelConfig, isMetaActive: !pixelConfig.isMetaActive })
                  }
                  className={`px-3 py-1 rounded-full text-xs font-black transition ${
                    pixelConfig.isMetaActive
                      ? 'bg-emerald-600 text-white shadow-sm'
                      : 'bg-slate-200 text-slate-600'
                  }`}
                >
                  {pixelConfig.isMetaActive ? 'Enabled' : 'Disabled'}
                </button>
              </div>
              <input
                type="text"
                value={pixelConfig.metaPixelId || ''}
                onChange={(e) => setPixelConfig({ ...pixelConfig, metaPixelId: e.target.value })}
                placeholder="e.g. 123456789012345"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-white text-xs font-mono font-bold text-indigo-600"
              />
            </div>

            {/* TikTok Pixel */}
            <div className="p-5 rounded-2xl bg-slate-50 dark:bg-accent/40 border border-slate-200 dark:border-border space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="font-black text-sm text-slate-900 dark:text-foreground">
                    TikTok Ads Pixel
                  </span>
                  <button
                    type="button"
                    onClick={() => setActivePixelGuide(PIXEL_HELP_GUIDES.tiktok)}
                    className="p-1 rounded-full text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 dark:hover:bg-indigo-950/50 transition cursor-pointer"
                    title="Learn what TikTok Pixel does and how to get your Pixel ID"
                  >
                    <Info className="w-4 h-4 text-indigo-500" />
                  </button>
                </div>
                <button
                  type="button"
                  onClick={() =>
                    setPixelConfig({ ...pixelConfig, isTikTokActive: !pixelConfig.isTikTokActive })
                  }
                  className={`px-3 py-1 rounded-full text-xs font-black transition ${
                    pixelConfig.isTikTokActive
                      ? 'bg-emerald-600 text-white shadow-sm'
                      : 'bg-slate-200 text-slate-600'
                  }`}
                >
                  {pixelConfig.isTikTokActive ? 'Enabled' : 'Disabled'}
                </button>
              </div>
              <input
                type="text"
                value={pixelConfig.tikTokPixelId || ''}
                onChange={(e) => setPixelConfig({ ...pixelConfig, tikTokPixelId: e.target.value })}
                placeholder="e.g. C1234567890123456789"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-white text-xs font-mono font-bold text-indigo-600"
              />
            </div>

            {/* Pinterest Tag */}
            <div className="p-5 rounded-2xl bg-slate-50 dark:bg-accent/40 border border-slate-200 dark:border-border space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="font-black text-sm text-slate-900 dark:text-foreground">
                    Pinterest Tag
                  </span>
                  <button
                    type="button"
                    onClick={() => setActivePixelGuide(PIXEL_HELP_GUIDES.pinterest)}
                    className="p-1 rounded-full text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 dark:hover:bg-indigo-950/50 transition cursor-pointer"
                    title="Learn what Pinterest Tag does and how to get your Tag ID"
                  >
                    <Info className="w-4 h-4 text-indigo-500" />
                  </button>
                </div>
                <button
                  type="button"
                  onClick={() =>
                    setPixelConfig({
                      ...pixelConfig,
                      isPinterestActive: !pixelConfig.isPinterestActive,
                    })
                  }
                  className={`px-3 py-1 rounded-full text-xs font-black transition ${
                    pixelConfig.isPinterestActive
                      ? 'bg-emerald-600 text-white shadow-sm'
                      : 'bg-slate-200 text-slate-600'
                  }`}
                >
                  {pixelConfig.isPinterestActive ? 'Enabled' : 'Disabled'}
                </button>
              </div>
              <input
                type="text"
                value={pixelConfig.pinterestTagId || ''}
                onChange={(e) => setPixelConfig({ ...pixelConfig, pinterestTagId: e.target.value })}
                placeholder="e.g. 2612345678901"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-white text-xs font-mono font-bold text-indigo-600"
              />
            </div>

            {/* Adobe Analytics / Adobe Experience Platform */}
            <div className="p-5 rounded-2xl bg-slate-50 dark:bg-accent/40 border border-slate-200 dark:border-border space-y-3">
              <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <div className="flex items-center gap-2">
                    <span className="font-black text-sm text-slate-900 dark:text-foreground block">
                      Adobe Analytics (Launch / AEP)
                    </span>
                    <button
                      type="button"
                      onClick={() => setActivePixelGuide(PIXEL_HELP_GUIDES.adobe)}
                      className="p-1 rounded-full text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 dark:hover:bg-indigo-950/50 transition cursor-pointer"
                      title="Learn what Adobe Launch does and how to get your script URL"
                    >
                      <Info className="w-4 h-4 text-indigo-500" />
                    </button>
                  </div>
                  <span className="text-[11px] text-slate-500">
                    Adobe Launch Header Script URL (assets.adobedtm.com/...)
                  </span>
                </div>
                <button
                  type="button"
                  onClick={() =>
                    setPixelConfig({
                      ...pixelConfig,
                      isAdobeActive: !pixelConfig.isAdobeActive,
                    })
                  }
                  className={`px-3 py-1 rounded-full text-xs font-black transition ${
                    pixelConfig.isAdobeActive
                      ? 'bg-emerald-600 text-white shadow-sm'
                      : 'bg-slate-200 text-slate-600'
                  }`}
                >
                  {pixelConfig.isAdobeActive ? 'Enabled' : 'Disabled'}
                </button>
              </div>
              <input
                type="text"
                value={pixelConfig.adobeLaunchUrl || ''}
                onChange={(e) => setPixelConfig({ ...pixelConfig, adobeLaunchUrl: e.target.value })}
                placeholder="https://assets.adobedtm.com/launch-ENxxxxxxxxxxxx-production.min.js"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-white text-xs font-mono font-bold text-indigo-600"
              />
            </div>

            {/* CleverTap Customer Engagement & Retention */}
            <div className="p-5 rounded-2xl bg-slate-50 dark:bg-accent/40 border border-slate-200 dark:border-border space-y-3">
              <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <div className="flex items-center gap-2">
                    <span className="font-black text-sm text-slate-900 dark:text-foreground block">
                      CleverTap Customer Engagement
                    </span>
                    <button
                      type="button"
                      onClick={() => setActivePixelGuide(PIXEL_HELP_GUIDES.clevertap)}
                      className="p-1 rounded-full text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 dark:hover:bg-indigo-950/50 transition cursor-pointer"
                      title="Learn what CleverTap does and how to get your Account ID"
                    >
                      <Info className="w-4 h-4 text-indigo-500" />
                    </button>
                  </div>
                  <span className="text-[11px] text-slate-500">
                    Real-time user journeys, event tracking, and cart recovery
                  </span>
                </div>
                <button
                  type="button"
                  onClick={() =>
                    setPixelConfig({
                      ...pixelConfig,
                      isCleverTapActive: !pixelConfig.isCleverTapActive,
                    })
                  }
                  className={`px-3 py-1 rounded-full text-xs font-black transition ${
                    pixelConfig.isCleverTapActive
                      ? 'bg-emerald-600 text-white shadow-sm'
                      : 'bg-slate-200 text-slate-600'
                  }`}
                >
                  {pixelConfig.isCleverTapActive ? 'Enabled' : 'Disabled'}
                </button>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="space-y-1 sm:col-span-1">
                  <label className="text-[11px] font-bold text-slate-600 dark:text-slate-400">
                    Account ID
                  </label>
                  <input
                    type="text"
                    value={pixelConfig.cleverTapAccountId || ''}
                    onChange={(e) =>
                      setPixelConfig({ ...pixelConfig, cleverTapAccountId: e.target.value })
                    }
                    placeholder="e.g. W9R-444-TEST"
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 bg-white text-xs font-mono font-bold text-indigo-600"
                  />
                </div>
                <div className="space-y-1 sm:col-span-1">
                  <label className="text-[11px] font-bold text-slate-600 dark:text-slate-400">
                    Passcode / Token (Optional)
                  </label>
                  <input
                    type="text"
                    value={pixelConfig.cleverTapToken || ''}
                    onChange={(e) =>
                      setPixelConfig({ ...pixelConfig, cleverTapToken: e.target.value })
                    }
                    placeholder="e.g. 660-000"
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 bg-white text-xs font-mono font-bold text-indigo-600"
                  />
                </div>
                <div className="space-y-1 sm:col-span-1">
                  <label className="text-[11px] font-bold text-slate-600 dark:text-slate-400">
                    Region Cluster
                  </label>
                  <select
                    value={pixelConfig.cleverTapRegion || 'in1'}
                    onChange={(e) =>
                      setPixelConfig({ ...pixelConfig, cleverTapRegion: e.target.value })
                    }
                    className="w-full px-3 py-2 rounded-xl border border-slate-200 bg-white text-xs font-bold text-slate-700 dark:bg-card"
                  >
                    <option value="in1">India (in1)</option>
                    <option value="us1">United States (us1)</option>
                    <option value="sg1">Singapore (sg1)</option>
                    <option value="eu1">Europe (eu1)</option>
                    <option value="sk1">Middle East (sk1)</option>
                  </select>
                </div>
              </div>
            </div>
          </div>

          <div className="flex justify-end pt-3">
            <button
              type="submit"
              disabled={isSaving}
              className="px-6 py-2.5 rounded-2xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-extrabold shadow-md flex items-center gap-2"
            >
              <CheckCircle2 className="w-4 h-4" />
              <span>Save Pixel Configurations</span>
            </button>
          </div>
        </form>
      )}

      {/* 4. UTM BUILDER TAB */}
      {activeTab === 'UTM' && (
        <div className="p-6 rounded-3xl border border-slate-200/80 dark:border-border bg-white dark:bg-card shadow-sm space-y-6">
          <div className="space-y-1 border-b pb-4">
            <h3 className="font-black text-lg text-slate-900 dark:text-foreground flex items-center gap-2">
              <Share2 className="w-5 h-5 text-indigo-600" />
              <span>UTM Campaign Link Builder</span>
            </h3>
            <p className="text-xs text-slate-500">
              Generate tracking URLs for paid Google Search, Meta Ads, Newsletter blasts, & Social
              influencers.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-1.5 md:col-span-2">
              <label className="block text-xs font-bold text-slate-700">
                Target Storefront Page URL *
              </label>
              <input
                type="url"
                value={utmUrl}
                onChange={(e) => setUtmUrl(e.target.value)}
                placeholder="https://yourstore.com/products/example"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-mono font-bold"
              />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-700">
                UTM Source (utm_source) *
              </label>
              <input
                type="text"
                value={utmSource}
                onChange={(e) => setUtmSource(e.target.value)}
                placeholder="google, facebook, newsletter"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-semibold"
              />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-700">
                UTM Medium (utm_medium) *
              </label>
              <input
                type="text"
                value={utmMedium}
                onChange={(e) => setUtmMedium(e.target.value)}
                placeholder="cpc, banner, email"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-semibold"
              />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-700">
                UTM Campaign (utm_campaign) *
              </label>
              <input
                type="text"
                value={utmCampaign}
                onChange={(e) => setUtmCampaign(e.target.value)}
                placeholder="summer_sale_2026"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-semibold"
              />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-700">UTM Term (utm_term)</label>
              <input
                type="text"
                value={utmTerm}
                onChange={(e) => setUtmTerm(e.target.value)}
                placeholder="wireless_headphones"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-semibold"
              />
            </div>
          </div>

          {/* GENERATED RESULT BOX */}
          <div className="p-5 rounded-2xl bg-slate-900 text-white space-y-3">
            <span className="text-[11px] font-black uppercase tracking-wider text-amber-400 block">
              Generated Campaign Tracking URL
            </span>
            <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800 font-mono text-xs text-indigo-300 break-all">
              {generatedUtmUrl ||
                'Enter your target URL and campaign parameters above to generate a tracking link.'}
            </div>
            <div className="flex justify-end">
              <button
                type="button"
                onClick={handleCopyUtm}
                className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-extrabold flex items-center gap-1.5"
              >
                {copiedUtm ? (
                  <Check className="w-4 h-4 text-emerald-400" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
                <span>{copiedUtm ? 'Copied!' : 'Copy Tracking Link'}</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* CREATE CAMPAIGN BROADCAST MODAL */}
      {isCampaignModalOpen && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-xs flex items-center justify-center p-4 animate-in fade-in">
          <div className="bg-white dark:bg-card border border-slate-200 dark:border-border rounded-3xl w-full max-w-md shadow-2xl overflow-hidden">
            <div className="p-6 bg-slate-900 text-white flex items-center justify-between">
              <h3 className="font-black text-lg">Create Campaign Broadcast</h3>
              <button
                type="button"
                onClick={() => setIsCampaignModalOpen(false)}
                className="p-2 rounded-xl hover:bg-white/10 text-slate-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleSaveCampaign} className="p-6 space-y-4">
              <div className="space-y-1.5">
                <label className="block text-xs font-bold text-slate-700">Broadcast Title *</label>
                <input
                  type="text"
                  required
                  value={campaignForm.title}
                  onChange={(e) => setCampaignForm({ ...campaignForm, title: e.target.value })}
                  placeholder="e.g. Summer Mega Sale Blast"
                  className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-bold"
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="block text-xs font-bold text-slate-700">Channel</label>
                  <select
                    value={campaignForm.channel}
                    onChange={(e) =>
                      setCampaignForm({
                        ...campaignForm,
                        channel: e.target.value as MarketingChannel,
                      })
                    }
                    className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-bold"
                  >
                    <option value="EMAIL">EMAIL</option>
                    <option value="SMS">SMS</option>
                    <option value="WHATSAPP">WHATSAPP</option>
                    <option value="PUSH">WEB PUSH</option>
                  </select>
                </div>

                <div className="space-y-1.5">
                  <label className="block text-xs font-bold text-slate-700">Target Audience</label>
                  <select
                    value={campaignForm.targetSegment}
                    onChange={(e) =>
                      setCampaignForm({ ...campaignForm, targetSegment: e.target.value })
                    }
                    className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-bold"
                  >
                    <option value="All Customers">All Customers</option>
                    <option value="VIP High Spenders">VIP Customers</option>
                    <option value="Cart Abandoners">Cart Abandoners</option>
                  </select>
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="block text-xs font-bold text-slate-700">Subject / Header</label>
                <input
                  type="text"
                  required
                  value={campaignForm.subject}
                  onChange={(e) => setCampaignForm({ ...campaignForm, subject: e.target.value })}
                  className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-semibold"
                />
              </div>

              <div className="space-y-1.5">
                <div className="flex justify-between items-center text-xs font-bold text-slate-700">
                  <span>Message Body</span>
                  {campaignForm.channel === 'SMS' && (
                    <span className="text-[10px] font-mono text-indigo-600">
                      {campaignForm.body.length}/160 chars
                    </span>
                  )}
                </div>
                <textarea
                  rows={3}
                  required
                  value={campaignForm.body}
                  onChange={(e) => setCampaignForm({ ...campaignForm, body: e.target.value })}
                  className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 bg-slate-50 text-xs font-medium"
                />
              </div>

              <div className="flex items-center justify-end gap-3 pt-3">
                <button
                  type="button"
                  onClick={() => setIsCampaignModalOpen(false)}
                  className="px-5 py-2.5 rounded-2xl bg-slate-100 text-slate-700 text-xs font-bold"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSaving}
                  className="px-6 py-2.5 rounded-2xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-extrabold shadow-md flex items-center gap-2"
                >
                  <Send className="w-4 h-4" />
                  <span>Send Broadcast Now</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Pixel Help & Setup Guide Modal */}
      {activePixelGuide && (() => {
        const guide = activePixelGuide;
        const allGuides = Object.values(PIXEL_HELP_GUIDES);
        return (
          <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
            <div className="bg-white dark:bg-card border border-slate-200 dark:border-border rounded-3xl max-w-2xl w-full p-6 sm:p-8 space-y-6 shadow-2xl relative animate-in fade-in zoom-in-95 my-8 max-h-[90vh] overflow-y-auto">
              
              {/* Modal Header */}
              <div className="flex items-start justify-between gap-4 pb-4 border-b border-slate-100 dark:border-border">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-bold border ${guide.badgeBg}`}>
                      <Sparkles className="w-3 h-3" />
                      {guide.badgeText}
                    </span>
                    <span className="text-[11px] font-medium text-slate-400 dark:text-muted-foreground">
                      {guide.category}
                    </span>
                  </div>
                  <h3 className="text-xl font-extrabold text-slate-900 dark:text-foreground">
                    {guide.name}
                  </h3>
                  <p className="text-xs text-slate-500 dark:text-muted-foreground leading-relaxed pt-1">
                    {guide.summary}
                  </p>
                </div>
                <button
                  type="button"
                  onClick={() => setActivePixelGuide(null)}
                  className="p-2 rounded-xl text-slate-400 hover:text-slate-600 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
                  title="Close Guide"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Provider Quick Tabs */}
              <div className="flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none">
                {allGuides.map((g) => {
                  const isActive = g.id === guide.id;
                  return (
                    <button
                      key={g.id}
                      type="button"
                      onClick={() => setActivePixelGuide(g)}
                      className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-all flex items-center gap-1.5 ${
                        isActive
                          ? 'bg-indigo-600 text-white shadow-sm shadow-indigo-200 dark:shadow-none'
                          : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700'
                      }`}
                    >
                      <span>{g.name.split(' ')[0]}</span>
                    </button>
                  );
                })}
              </div>

              {/* Section 1: What it does */}
              <div className="space-y-2.5 bg-slate-50 dark:bg-slate-900/50 p-4 rounded-2xl border border-slate-100 dark:border-border/60">
                <div className="flex items-center gap-2 text-xs font-bold text-slate-900 dark:text-foreground">
                  <div className="p-1 rounded-lg bg-indigo-100 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400">
                    <Target className="w-3.5 h-3.5" />
                  </div>
                  <span>What It Does & Why You Need It</span>
                </div>
                <ul className="space-y-1.5">
                  {guide.whatItDoes.map((item: string, idx: number) => (
                    <li key={idx} className="text-xs text-slate-600 dark:text-slate-300 flex items-start gap-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 flex-shrink-0" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Section 2: How to use / automated storefront events */}
              <div className="space-y-2.5 bg-slate-50 dark:bg-slate-900/50 p-4 rounded-2xl border border-slate-100 dark:border-border/60">
                <div className="flex items-center gap-2 text-xs font-bold text-slate-900 dark:text-foreground">
                  <div className="p-1 rounded-lg bg-emerald-100 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400">
                    <Zap className="w-3.5 h-3.5" />
                  </div>
                  <span>How To Use & Automated Storefront Events</span>
                </div>
                <ul className="space-y-1.5">
                  {guide.howToUse.map((item: string, idx: number) => (
                    <li key={idx} className="text-xs text-slate-600 dark:text-slate-300 flex items-start gap-2">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 mt-0.5 flex-shrink-0" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Section 3: Step-by-step key acquisition instructions */}
              <div className="space-y-3 bg-indigo-50/50 dark:bg-indigo-950/20 p-4 rounded-2xl border border-indigo-100 dark:border-indigo-900/40">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-xs font-bold text-indigo-950 dark:text-indigo-200">
                    <div className="p-1 rounded-lg bg-indigo-200 dark:bg-indigo-900 text-indigo-700 dark:text-indigo-300">
                      <Key className="w-3.5 h-3.5" />
                    </div>
                    <span>How To Get Your Access Key / ID</span>
                  </div>
                  <a
                    href={guide.howToGetAccessKey.portalUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1.5 text-[11px] font-bold text-indigo-600 dark:text-indigo-400 hover:underline"
                  >
                    <span>{guide.howToGetAccessKey.portalName}</span>
                    <ExternalLink className="w-3 h-3" />
                  </a>
                </div>

                <div className="space-y-2">
                  {guide.howToGetAccessKey.steps.map((step: string, idx: number) => (
                    <div key={idx} className="flex items-start gap-2.5 text-xs text-slate-700 dark:text-slate-300">
                      <span className="w-5 h-5 rounded-full bg-indigo-200 dark:bg-indigo-900/80 text-indigo-800 dark:text-indigo-200 font-extrabold text-[10px] flex items-center justify-center flex-shrink-0 mt-0.5">
                        {idx + 1}
                      </span>
                      <span className="leading-snug">{step}</span>
                    </div>
                  ))}
                </div>

                {/* Key Format Card */}
                <div className="mt-3 p-3 rounded-xl bg-white dark:bg-card border border-indigo-100 dark:border-indigo-900/60 flex items-center justify-between gap-3">
                  <div className="space-y-0.5">
                    <div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                      Expected ID Format
                    </div>
                    <div className="font-mono text-xs font-bold text-indigo-600 dark:text-indigo-400 break-all">
                      {guide.howToGetAccessKey.formatExample}
                    </div>
                  </div>
                  <a
                    href={guide.howToGetAccessKey.portalUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-[11px] font-bold flex items-center gap-1 flex-shrink-0 shadow-sm"
                  >
                    <span>Get Key</span>
                    <ExternalLink className="w-3 h-3" />
                  </a>
                </div>
              </div>

              {/* Modal Footer */}
              <div className="flex items-center justify-between pt-2">
                <div className="text-[11px] text-slate-400 flex items-center gap-1.5">
                  <ShieldCheck className="w-3.5 h-3.5 text-emerald-500" />
                  <span>Configured keys are saved securely for your store</span>
                </div>
                <button
                  type="button"
                  onClick={() => setActivePixelGuide(null)}
                  className="px-5 py-2.5 rounded-2xl bg-slate-900 hover:bg-slate-800 dark:bg-slate-100 dark:hover:bg-slate-200 text-white dark:text-slate-900 text-xs font-bold transition"
                >
                  Got It, Thanks
                </button>
              </div>

            </div>
          </div>
        );
      })()}
    </div>
  );
};

