'use client';

import React, { useState, useEffect } from 'react';
import { cmsService } from '@/src/services/cmsService';
import {
  Mail,
  Send,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
  Eye,
  EyeOff,
  ExternalLink,
  ShieldCheck,
  Sparkles,
  Server,
  KeyRound,
  HelpCircle,
  Check,
  Lock,
  Globe,
  Crown,
  ChevronDown,
  ChevronUp,
  Info,
  Copy,
} from 'lucide-react';

interface VendorSmtpSettingsProps {
  storeId?: string;
  onSaved?: () => void;
}

interface ProviderPreset {
  id: string;
  name: string;
  badge: string;
  defaultHost: string;
  defaultPort: number;
  secure: boolean;
  requiresAppPassword?: boolean;
  helpUrl?: string;
  description: string;
  icon: string;
  steps: { title: string; instruction: string; link?: string; linkText?: string }[];
}

const DEFAULT_PRESETS: Record<string, ProviderPreset> = {
  gmail: {
    id: 'gmail',
    name: 'Google Gmail / Workspace',
    badge: 'Recommended',
    defaultHost: 'smtp.gmail.com',
    defaultPort: 465,
    secure: true,
    requiresAppPassword: true,
    helpUrl: 'https://myaccount.google.com/apppasswords',
    description: 'Send through your Google Account or Google Workspace custom domain using a 16-character App Password.',
    icon: '🔴',
    steps: [
      {
        title: 'Step 1: Turn ON 2-Step Verification',
        instruction: 'Go to your Google Account Security settings and make sure 2-Step Verification is enabled on your account.',
        link: 'https://myaccount.google.com/security',
        linkText: 'Google Security Settings ↗',
      },
      {
        title: 'Step 2: Generate an App Password',
        instruction: 'Navigate to App Passwords. Give your password a name like "OmniStore CMS" and click Create.',
        link: 'https://myaccount.google.com/apppasswords',
        linkText: 'Direct App Passwords Page ↗',
      },
      {
        title: 'Step 3: Copy 16-Character Password',
        instruction: 'Copy the yellow 16-letter code generated by Google (e.g., abcd efgh ijkl mnop). Spaces are automatically stripped.',
      },
      {
        title: 'Step 4: Paste and Save',
        instruction: 'Paste your Gmail address as Sender Email and the 16-character code as App Password below.',
      },
    ],
  },
  outlook: {
    id: 'outlook',
    name: 'Microsoft Outlook / 365',
    badge: 'Enterprise',
    defaultHost: 'smtp.office365.com',
    defaultPort: 587,
    secure: false,
    requiresAppPassword: true,
    helpUrl: 'https://account.microsoft.com/security',
    description: 'Personal Outlook/Hotmail or enterprise Microsoft 365 Exchange accounts.',
    icon: '🟦',
    steps: [
      {
        title: 'Step 1: Open Microsoft Account Security',
        instruction: 'Log into your Microsoft account and open Advanced Security Options.',
        link: 'https://account.microsoft.com/security',
        linkText: 'Microsoft Security Dashboard ↗',
      },
      {
        title: 'Step 2: Create App Password',
        instruction: 'Under the App Passwords section, click "Create a new app password".',
      },
      {
        title: 'Step 3: Use Port 587 (STARTTLS)',
        instruction: 'Use smtp.office365.com with Port 587. Enter your full Microsoft email and generated app password.',
      },
    ],
  },
  yahoo: {
    id: 'yahoo',
    name: 'Yahoo Mail',
    badge: 'Standard',
    defaultHost: 'smtp.mail.yahoo.com',
    defaultPort: 465,
    secure: true,
    requiresAppPassword: true,
    helpUrl: 'https://login.yahoo.com/account/security',
    description: 'Yahoo Mail accounts with dedicated third-party App Passwords.',
    icon: '🟣',
    steps: [
      {
        title: 'Step 1: Access Yahoo Account Security',
        instruction: 'Sign in to Yahoo and navigate to Account Security.',
        link: 'https://login.yahoo.com/account/security',
        linkText: 'Yahoo Account Security ↗',
      },
      {
        title: 'Step 2: Generate App Password',
        instruction: 'Click "Generate and manage app passwords", enter app name "CMS Mail", and generate.',
      },
      {
        title: 'Step 3: Paste and Test',
        instruction: 'Enter your Yahoo email and generated password below with Host smtp.mail.yahoo.com and Port 465.',
      },
    ],
  },
  zoho: {
    id: 'zoho',
    name: 'Zoho Mail',
    badge: 'Business',
    defaultHost: 'smtp.zoho.com',
    defaultPort: 465,
    secure: true,
    requiresAppPassword: true,
    helpUrl: 'https://accounts.zoho.com/home#security',
    description: 'Zoho Mail personal and custom business domains hosted on Zoho.',
    icon: '🟧',
    steps: [
      {
        title: 'Step 1: Open Zoho Security Center',
        instruction: 'Go to Zoho Accounts and click Security in the left navigation.',
        link: 'https://accounts.zoho.com/home#security',
        linkText: 'Zoho Accounts Security ↗',
      },
      {
        title: 'Step 2: Application-Specific Password',
        instruction: 'Click Application-Specific Passwords → Generate New Password.',
      },
      {
        title: 'Step 3: Connect Credentials',
        instruction: 'Enter your Zoho email and the generated password into the form below.',
      },
    ],
  },
  icloud: {
    id: 'icloud',
    name: 'Apple iCloud',
    badge: 'Apple',
    defaultHost: 'smtp.mail.me.com',
    defaultPort: 587,
    secure: false,
    requiresAppPassword: true,
    helpUrl: 'https://appleid.apple.com/account/manage',
    description: 'Apple iCloud accounts (@icloud.com, @me.com, @mac.com).',
    icon: '🍏',
    steps: [
      {
        title: 'Step 1: Sign in to Apple ID',
        instruction: 'Log in to your Apple ID management page.',
        link: 'https://appleid.apple.com/account/manage',
        linkText: 'Apple ID Portal ↗',
      },
      {
        title: 'Step 2: Create App-Specific Password',
        instruction: 'In the Sign-In and Security section, select App-Specific Passwords and generate one.',
      },
      {
        title: 'Step 3: Enter Details',
        instruction: 'Use smtp.mail.me.com on Port 587 with your iCloud email and app-specific password.',
      },
    ],
  },
  custom: {
    id: 'custom',
    name: 'Custom SMTP / AWS / cPanel',
    badge: 'Self-Hosted',
    defaultHost: 'mail.yourdomain.com',
    defaultPort: 465,
    secure: true,
    description: 'Direct SMTP server on your hosting provider (cPanel, GoDaddy, Hostinger, Amazon SES, SendGrid, Mailgun).',
    icon: '⚙️',
    steps: [
      {
        title: 'Step 1: Retrieve SMTP Server Host',
        instruction: 'Find your Outgoing Mail Server (e.g., mail.yourdomain.com, email-smtp.us-east-1.amazonaws.com, or smtp.sendgrid.net).',
      },
      {
        title: 'Step 2: Choose SSL/TLS Port',
        instruction: 'Use Port 465 with SSL enabled (Recommended) or Port 587 with STARTTLS.',
      },
      {
        title: 'Step 3: Authenticate Credentials',
        instruction: 'Enter your full mailbox email / API Key username and secret password.',
      },
    ],
  },
};

export const VendorSmtpSettings: React.FC<VendorSmtpSettingsProps> = ({ storeId, onSaved }) => {
  const [smtpConfig, setSmtpConfig] = useState({
    smtpHost: '',
    smtpPort: 465,
    smtpSecure: true,
    smtpUser: '',
    smtpPass: '',
    smtpFromName: '',
    smtpFromEmail: '',
    smtpService: 'gmail',
    smtpEnabled: true,
    hasPassword: false,
  });

  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [isGuideOpen, setIsGuideOpen] = useState(true);
  const [copiedLink, setCopiedLink] = useState(false);

  // Test Email States
  const [testEmailRecipient, setTestEmailRecipient] = useState('');
  const [isTesting, setIsTesting] = useState(false);
  const [testResult, setTestResult] = useState<{
    success: boolean;
    delivered: boolean;
    simulated: boolean;
    message: string;
    provider?: string;
    error?: string;
  } | null>(null);

  const [toastMessage, setToastMessage] = useState<{
    text: string;
    type: 'success' | 'error';
  } | null>(null);

  useEffect(() => {
    loadSmtpSettings();
  }, [storeId]);

  const loadSmtpSettings = async () => {
    setIsLoading(true);
    try {
      const data = await cmsService.getStoreSmtpConfig(storeId);
      setSmtpConfig({
        smtpHost: data.smtpHost || DEFAULT_PRESETS.gmail.defaultHost,
        smtpPort: data.smtpPort || DEFAULT_PRESETS.gmail.defaultPort,
        smtpSecure: data.smtpSecure ?? true,
        smtpUser: data.smtpUser || '',
        smtpPass: '', // never expose existing password plain-text
        smtpFromName: data.smtpFromName || data.storeName || '',
        smtpFromEmail: data.smtpFromEmail || data.smtpUser || '',
        smtpService: data.smtpService || 'gmail',
        smtpEnabled: data.smtpEnabled ?? false,
        hasPassword: data.hasPassword ?? false,
      });
      if (data.smtpUser && !testEmailRecipient) {
        setTestEmailRecipient(data.smtpUser);
      }
    } catch (err) {
      console.error('Failed to load store SMTP settings:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const showToast = (text: string, type: 'success' | 'error' = 'success') => {
    setToastMessage({ text, type });
    setTimeout(() => setToastMessage(null), 4000);
  };

  const handleProviderSelect = (providerKey: string) => {
    const preset = DEFAULT_PRESETS[providerKey] || DEFAULT_PRESETS.custom;
    setSmtpConfig((prev) => ({
      ...prev,
      smtpService: providerKey,
      smtpHost: preset.defaultHost,
      smtpPort: preset.defaultPort,
      smtpSecure: preset.secure,
    }));
  };

  const handleSave = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setIsSaving(true);
    try {
      const updated = await cmsService.updateStoreSmtpConfig(
        {
          smtpHost: smtpConfig.smtpHost,
          smtpPort: smtpConfig.smtpPort,
          smtpSecure: smtpConfig.smtpSecure,
          smtpUser: smtpConfig.smtpUser,
          smtpPass: smtpConfig.smtpPass,
          smtpFromName: smtpConfig.smtpFromName,
          smtpFromEmail: smtpConfig.smtpFromEmail,
          smtpService: smtpConfig.smtpService,
          smtpEnabled: smtpConfig.smtpEnabled,
        },
        storeId,
      );

      setSmtpConfig((prev) => ({
        ...prev,
        hasPassword: updated.hasPassword,
        smtpPass: '', // Clear password field after saving
      }));

      showToast('Owner SMTP delivery credentials securely saved and verified!');
      if (onSaved) onSaved();
    } catch (err: any) {
      showToast(err?.message || 'Failed to save SMTP configuration', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  const handleSendTestEmail = async () => {
    if (!testEmailRecipient || !testEmailRecipient.includes('@')) {
      showToast('Please enter a valid recipient email to send the test.', 'error');
      return;
    }

    setIsTesting(true);
    setTestResult(null);

    try {
      const result = await cmsService.testStoreSmtpConfig(
        {
          testEmail: testEmailRecipient,
          smtpHost: smtpConfig.smtpHost,
          smtpPort: smtpConfig.smtpPort,
          smtpSecure: smtpConfig.smtpSecure,
          smtpUser: smtpConfig.smtpUser,
          smtpPass: smtpConfig.smtpPass,
          smtpFromName: smtpConfig.smtpFromName,
          smtpFromEmail: smtpConfig.smtpFromEmail,
          smtpService: smtpConfig.smtpService,
          smtpEnabled: true,
        },
        storeId,
      );

      setTestResult(result);
      if (result.success && result.delivered) {
        showToast('Test email delivered successfully to your inbox!');
      } else if (!result.success) {
        showToast('SMTP Test failed. Check error diagnostics below.', 'error');
      }
    } catch (err: any) {
      setTestResult({
        success: false,
        delivered: false,
        simulated: false,
        message: err?.response?.data?.message || err.message || 'SMTP Connection failed',
        error: err?.message,
      });
      showToast('Failed to connect to mail server', 'error');
    } finally {
      setIsTesting(false);
    }
  };

  const currentPreset = DEFAULT_PRESETS[smtpConfig.smtpService] || DEFAULT_PRESETS.custom;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-12 bg-white dark:bg-card border border-slate-200/80 dark:border-border rounded-3xl">
        <RefreshCw className="w-6 h-6 animate-spin text-indigo-600" />
        <span className="ml-3 text-xs font-bold text-slate-500 animate-pulse">
          Loading email delivery settings...
        </span>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Toast Notification */}
      {toastMessage && (
        <div
          className={`fixed bottom-6 right-6 z-50 flex items-center gap-3 px-5 py-3.5 rounded-2xl shadow-xl border text-xs font-bold backdrop-blur-md transition-all animate-in slide-in-from-bottom-5 ${
            toastMessage.type === 'success'
              ? 'bg-emerald-900/90 text-white border-emerald-700'
              : 'bg-rose-900/90 text-white border-rose-700'
          }`}
        >
          {toastMessage.type === 'success' ? (
            <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
          ) : (
            <AlertCircle className="w-5 h-5 text-rose-400 shrink-0" />
          )}
          <span>{toastMessage.text}</span>
        </div>
      )}

      {/* ─── PRIVILEGE & OWNER AUTHORIZATION BANNER ─────────────────────── */}
      <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-sm space-y-4 relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <div className="flex flex-wrap items-center gap-2">
              <span className="px-3 py-1 rounded-full bg-amber-50 text-amber-800 dark:bg-amber-950/60 dark:text-amber-300 font-extrabold text-[11px] uppercase tracking-wider border border-amber-200/80 dark:border-amber-800/60 flex items-center gap-1.5">
                <Crown className="w-3.5 h-3.5 text-amber-500" />
                <span>Store Owner Privilege</span>
              </span>
              <span className="px-2.5 py-0.5 rounded-full bg-indigo-50 text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300 text-[10px] font-bold border border-indigo-200/80 dark:border-indigo-800/60 flex items-center gap-1">
                <ShieldCheck className="w-3.5 h-3.5 text-indigo-600" />
                <span>AES-256 Encrypted Credential Vault</span>
              </span>
              {smtpConfig.hasPassword && smtpConfig.smtpEnabled ? (
                <span className="px-2.5 py-0.5 rounded-full bg-emerald-50 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-300 text-[10px] font-bold border border-emerald-200/80 dark:border-emerald-800/60 flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                  Custom SMTP Active
                </span>
              ) : (
                <span className="px-2.5 py-0.5 rounded-full bg-slate-100 text-slate-600 dark:bg-accent dark:text-slate-400 text-[10px] font-bold border border-slate-200 dark:border-border">
                  Platform Fallback Mode
                </span>
              )}
            </div>

            <h2 className="text-2xl sm:text-3xl font-black tracking-tight text-slate-900 dark:text-foreground flex items-center gap-3">
              <Mail className="w-8 h-8 text-indigo-600 dark:text-indigo-400" />
              <span>Owner SMTP & Dedicated Email Routing</span>
            </h2>

            <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 max-w-3xl leading-relaxed">
              As the verified store owner, configure your dedicated email sender credentials (Google Workspace, Gmail, Outlook, Yahoo, or Custom SMTP). All automated receipts, abandoned checkout recoveries, order tracking notices, and promotional newsletters will dispatch directly from your verified brand domain.
            </p>
          </div>

          <div className="flex items-center gap-3 shrink-0 bg-slate-50 dark:bg-accent/40 p-3 rounded-2xl border border-slate-200/80 dark:border-border/60">
            <label className="relative inline-flex items-center cursor-pointer">
              <input
                type="checkbox"
                checked={smtpConfig.smtpEnabled}
                onChange={(e) =>
                  setSmtpConfig((prev) => ({ ...prev, smtpEnabled: e.target.checked }))
                }
                className="sr-only peer"
              />
              <div className="w-11 h-6 bg-slate-200 peer-focus:outline-none rounded-full peer dark:bg-slate-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-indigo-600"></div>
              <span className="ml-2.5 text-xs font-black text-slate-900 dark:text-foreground">
                {smtpConfig.smtpEnabled ? 'Custom SMTP Enabled' : 'Disabled (Fallback)'}
              </span>
            </label>
          </div>
        </div>
      </div>

      {/* ─── STEP 1: SELECT PROVIDER ────────────────────────────────────── */}
      <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-sm space-y-5">
        <div className="flex items-center justify-between">
          <div>
            <span className="text-[11px] font-black uppercase tracking-wider text-indigo-600 dark:text-indigo-400 block">
              Step 1 of 3
            </span>
            <h3 className="text-lg font-black text-slate-900 dark:text-foreground">
              Select Your Email Mailbox Provider
            </h3>
          </div>
          <span className="text-xs text-slate-500 font-medium hidden sm:inline">
            Auto-fills host, port, and security protocols
          </span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
          {Object.values(DEFAULT_PRESETS).map((preset) => {
            const isSelected = smtpConfig.smtpService === preset.id;
            return (
              <button
                key={preset.id}
                type="button"
                onClick={() => handleProviderSelect(preset.id)}
                className={`flex flex-col items-center justify-center p-4 rounded-2xl border text-center transition-all cursor-pointer ${
                  isSelected
                    ? 'border-indigo-600 bg-indigo-50/60 dark:bg-indigo-950/40 text-indigo-950 dark:text-indigo-200 shadow-xs ring-2 ring-indigo-600/20'
                    : 'border-slate-200/80 dark:border-border bg-slate-50/50 dark:bg-accent/30 text-slate-700 dark:text-slate-300 hover:border-indigo-300 hover:bg-slate-100/60'
                }`}
              >
                <span className="text-2xl mb-1.5">{preset.icon}</span>
                <span className="text-xs font-extrabold leading-tight line-clamp-1">{preset.name}</span>
                <span className="text-[10px] font-bold text-slate-400 mt-1">Port {preset.defaultPort}</span>
              </button>
            );
          })}
        </div>

        {/* ─── DETAILED STEP-BY-STEP APP PASSWORD GUIDE ─────────────────── */}
        <div className="mt-4 rounded-2xl border border-indigo-200/80 dark:border-indigo-900/50 bg-gradient-to-br from-indigo-50/50 via-sky-50/30 to-white dark:from-indigo-950/20 dark:via-sky-950/10 dark:to-card overflow-hidden transition-all">
          <div
            onClick={() => setIsGuideOpen(!isGuideOpen)}
            className="p-4 sm:p-5 flex items-center justify-between cursor-pointer hover:bg-indigo-50/40 transition"
          >
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-indigo-600 text-white flex items-center justify-center font-bold text-sm shadow-xs">
                <HelpCircle className="w-5 h-5" />
              </div>
              <div>
                <h4 className="text-sm font-black text-slate-900 dark:text-foreground flex items-center gap-2">
                  <span>How to Get SMTP Credentials for {currentPreset.name}</span>
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-indigo-100 text-indigo-800 dark:bg-indigo-950 dark:text-indigo-300">
                    Step-by-Step Guide
                  </span>
                </h4>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  {currentPreset.description}
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2">
              {currentPreset.helpUrl && (
                <a
                  href={currentPreset.helpUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={(e) => e.stopPropagation()}
                  className="px-3 py-1.5 rounded-xl bg-white dark:bg-card hover:bg-slate-50 text-indigo-600 dark:text-indigo-400 border border-indigo-200 dark:border-indigo-800 text-xs font-bold shadow-xs flex items-center gap-1.5 transition"
                >
                  <span>Open Official Security Portal</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>
              )}
              <button
                type="button"
                className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
              >
                {isGuideOpen ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
              </button>
            </div>
          </div>

          {isGuideOpen && (
            <div className="p-5 sm:p-6 border-t border-indigo-100 dark:border-indigo-900/40 space-y-4 bg-white/60 dark:bg-card/60">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3.5">
                {currentPreset.steps.map((step, idx) => (
                  <div
                    key={idx}
                    className="p-4 rounded-2xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-xs space-y-2 flex flex-col justify-between"
                  >
                    <div className="space-y-1.5">
                      <div className="flex items-center gap-2">
                        <span className="w-6 h-6 rounded-full bg-indigo-50 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300 flex items-center justify-center text-xs font-black shrink-0 border border-indigo-200 dark:border-indigo-800">
                          {idx + 1}
                        </span>
                        <h5 className="font-black text-xs text-slate-900 dark:text-foreground">
                          {step.title}
                        </h5>
                      </div>
                      <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                        {step.instruction}
                      </p>
                    </div>

                    {step.link && (
                      <a
                        href={step.link}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-[11px] font-black text-indigo-600 dark:text-indigo-400 hover:underline pt-2 border-t border-slate-100 dark:border-border/40"
                      >
                        <span>{step.linkText || 'Open Link'}</span>
                        <ExternalLink className="w-3 h-3" />
                      </a>
                    )}
                  </div>
                ))}
              </div>

              {/* Security & Troubleshooting Notice */}
              <div className="p-4 rounded-2xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200/80 dark:border-amber-800/60 flex items-start gap-3">
                <Info className="w-5 h-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
                <div className="space-y-1 text-xs">
                  <p className="font-bold text-amber-900 dark:text-amber-200">
                    Important: Never use your master account password for SMTP
                  </p>
                  <p className="text-amber-800 dark:text-amber-300 leading-relaxed">
                    Modern mail providers (Google, Microsoft, Yahoo, Zoho) block direct password logins for security. You <strong>must</strong> generate a 16-character <strong>App Password</strong> with 2-Step Verification active. If you encounter an authentication error, confirm that 2-Step Verification is enabled before generating the App Password.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ─── STEP 2: CREDENTIALS & SENDER IDENTITY ──────────────────────── */}
      <form
        onSubmit={handleSave}
        className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-sm space-y-6"
      >
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-border/60 pb-4">
          <div>
            <span className="text-[11px] font-black uppercase tracking-wider text-indigo-600 dark:text-indigo-400 block">
              Step 2 of 3
            </span>
            <h3 className="text-lg font-black text-slate-900 dark:text-foreground">
              Account Credentials & Sender Identity
            </h3>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-500 font-medium">Encrypted Vault Storage</span>
            <Lock className="w-4 h-4 text-emerald-600" />
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
          <div className="space-y-1.5">
            <label className="block text-xs font-bold text-slate-800 dark:text-slate-200">
              Sender Brand Display Name <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              required
              value={smtpConfig.smtpFromName}
              onChange={(e) =>
                setSmtpConfig((prev) => ({ ...prev, smtpFromName: e.target.value }))
              }
              placeholder="e.g. Wendr Store Flagship or Sarah's Boutique"
              className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 dark:border-border bg-slate-50 dark:bg-accent/40 text-xs font-bold text-slate-900 dark:text-foreground focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:bg-white"
            />
            <p className="text-[10px] text-slate-400">
              The sender name displayed in the customer&apos;s email inbox.
            </p>
          </div>

          <div className="space-y-1.5">
            <label className="block text-xs font-bold text-slate-800 dark:text-slate-200">
              Sender Email Address / Username <span className="text-rose-500">*</span>
            </label>
            <input
              type="email"
              required
              value={smtpConfig.smtpUser}
              onChange={(e) => {
                const val = e.target.value;
                setSmtpConfig((prev) => ({
                  ...prev,
                  smtpUser: val,
                  smtpFromEmail: prev.smtpFromEmail || val,
                }));
                if (!testEmailRecipient) setTestEmailRecipient(val);
              }}
              placeholder="e.g. orders@yourdomain.com or brand@gmail.com"
              className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 dark:border-border bg-slate-50 dark:bg-accent/40 text-xs font-mono font-bold text-slate-900 dark:text-foreground focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:bg-white"
            />
            <p className="text-[10px] text-slate-400">
              Full authentication email address registered with your provider.
            </p>
          </div>

          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label className="block text-xs font-bold text-slate-800 dark:text-slate-200">
                16-Character App Password / SMTP Secret{' '}
                {smtpConfig.hasPassword ? (
                  <span className="text-emerald-600 font-bold">(Password Saved)</span>
                ) : (
                  <span className="text-rose-500">*</span>
                )}
              </label>
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="text-[11px] font-bold text-indigo-600 dark:text-indigo-400 hover:underline flex items-center gap-1 cursor-pointer"
              >
                {showPassword ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                <span>{showPassword ? 'Hide' : 'Show'}</span>
              </button>
            </div>
            <div className="relative">
              <input
                type={showPassword ? 'text' : 'password'}
                value={smtpConfig.smtpPass}
                onChange={(e) =>
                  setSmtpConfig((prev) => ({ ...prev, smtpPass: e.target.value }))
                }
                placeholder={
                  smtpConfig.hasPassword
                    ? '•••••••••••••••• (Leave blank to keep saved password)'
                    : '16-character App Password (e.g. abcd efgh ijkl mnop)'
                }
                className="w-full px-4 py-2.5 pr-10 rounded-2xl border border-slate-200 dark:border-border bg-slate-50 dark:bg-accent/40 text-xs font-mono font-bold text-slate-900 dark:text-foreground focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:bg-white"
              />
            </div>
            <p className="text-[10px] text-slate-400">
              Spaces are stripped automatically. Stored with AES-256 server-side encryption.
            </p>
          </div>

          <div className="space-y-1.5">
            <label className="block text-xs font-bold text-slate-800 dark:text-slate-200">
              Custom From / Reply-To Email
            </label>
            <input
              type="email"
              value={smtpConfig.smtpFromEmail}
              onChange={(e) =>
                setSmtpConfig((prev) => ({ ...prev, smtpFromEmail: e.target.value }))
              }
              placeholder="e.g. support@yourdomain.com (Defaults to Username)"
              className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 dark:border-border bg-slate-50 dark:bg-accent/40 text-xs font-mono font-bold text-slate-900 dark:text-foreground focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:bg-white"
            />
            <p className="text-[10px] text-slate-400">
              Optional override for the return/reply-to address.
            </p>
          </div>
        </div>

        {/* Server & Port Advanced Protocols */}
        <div className="pt-4 border-t border-slate-100 dark:border-border/60">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="sm:col-span-2 space-y-1.5">
              <label className="block text-xs font-bold text-slate-800 dark:text-slate-200">
                SMTP Server Host
              </label>
              <input
                type="text"
                value={smtpConfig.smtpHost}
                onChange={(e) =>
                  setSmtpConfig((prev) => ({ ...prev, smtpHost: e.target.value }))
                }
                placeholder="e.g. smtp.gmail.com"
                className="w-full px-4 py-2.5 rounded-2xl border border-slate-200 dark:border-border bg-slate-50 dark:bg-accent/40 text-xs font-mono font-bold text-slate-900 dark:text-foreground focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:bg-white"
              />
            </div>

            <div className="space-y-1.5">
              <label className="block text-xs font-bold text-slate-800 dark:text-slate-200">
                Port & Security Protocol
              </label>
              <div className="flex items-center gap-2">
                <input
                  type="number"
                  value={smtpConfig.smtpPort}
                  onChange={(e) =>
                    setSmtpConfig((prev) => ({
                      ...prev,
                      smtpPort: parseInt(e.target.value) || 465,
                      smtpSecure: parseInt(e.target.value) === 465,
                    }))
                  }
                  className="w-24 px-3.5 py-2.5 rounded-2xl border border-slate-200 dark:border-border bg-slate-50 dark:bg-accent/40 text-xs font-mono font-bold text-slate-900 dark:text-foreground focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:bg-white"
                />
                <span className="text-xs font-bold px-3 py-2 rounded-2xl bg-slate-100 dark:bg-accent text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-border flex-1 text-center">
                  {smtpConfig.smtpPort === 465 ? 'SSL (Port 465)' : 'STARTTLS (Port 587)'}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Action Button */}
        <div className="pt-2 flex justify-end">
          <button
            type="submit"
            disabled={isSaving}
            className="px-6 py-3 rounded-2xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-extrabold shadow-sm hover:shadow flex items-center gap-2 transition-all cursor-pointer transform active:scale-95 disabled:opacity-50"
          >
            {isSaving ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                <span>Encrypting & Saving...</span>
              </>
            ) : (
              <>
                <ShieldCheck className="w-4 h-4" />
                <span>Save Owner SMTP Credentials</span>
              </>
            )}
          </button>
        </div>
      </form>

      {/* ─── STEP 3: LIVE DIAGNOSTICS & TEST INBOX ──────────────────────── */}
      <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-card border border-slate-200/80 dark:border-border shadow-sm space-y-5">
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-border/60 pb-4">
          <div>
            <span className="text-[11px] font-black uppercase tracking-wider text-indigo-600 dark:text-indigo-400 block">
              Step 3 of 3
            </span>
            <h3 className="text-lg font-black text-slate-900 dark:text-foreground">
              Live Inbox Delivery Test & Diagnostics
            </h3>
          </div>
          <span className="text-xs text-slate-500 font-medium hidden sm:inline">
            Sends an immediate HTML sample email
          </span>
        </div>

        <p className="text-xs text-slate-500 dark:text-slate-400">
          Verify that your SMTP host handshake, TLS handshake, and App Password pass all DKIM/SPF anti-spam filters by dispatching a live test email.
        </p>

        <div className="flex flex-col sm:flex-row items-stretch gap-3">
          <div className="relative flex-1">
            <Mail className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
            <input
              type="email"
              value={testEmailRecipient}
              onChange={(e) => setTestEmailRecipient(e.target.value)}
              placeholder="Enter recipient email (e.g. your personal email to verify delivery)"
              className="w-full pl-10 pr-4 py-2.5 rounded-2xl border border-slate-200 dark:border-border bg-slate-50 dark:bg-accent/40 text-xs font-bold text-slate-900 dark:text-foreground focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:bg-white"
            />
          </div>

          <button
            type="button"
            onClick={handleSendTestEmail}
            disabled={isTesting || !testEmailRecipient}
            className="px-6 py-2.5 rounded-2xl bg-indigo-50 hover:bg-indigo-100 text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300 border border-indigo-200/80 dark:border-indigo-800/60 text-xs font-black shadow-xs flex items-center justify-center gap-2 transition cursor-pointer transform active:scale-95 disabled:opacity-50 shrink-0"
          >
            {isTesting ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                <span>Connecting to Mail Server...</span>
              </>
            ) : (
              <>
                <Send className="w-4 h-4" />
                <span>Send Test Email</span>
              </>
            )}
          </button>
        </div>

        {/* Test Diagnostics Box */}
        {testResult && (
          <div
            className={`p-5 rounded-2xl text-xs space-y-2 border animate-in fade-in duration-200 ${
              testResult.success && testResult.delivered
                ? 'bg-emerald-50 text-emerald-950 border-emerald-200/80 dark:bg-emerald-950/40 dark:border-emerald-800 dark:text-emerald-200'
                : 'bg-rose-50 text-rose-950 border-rose-200/80 dark:bg-rose-950/40 dark:border-rose-800 dark:text-rose-200'
            }`}
          >
            <div className="flex items-center gap-2 font-black">
              {testResult.success && testResult.delivered ? (
                <>
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
                  <span>Delivery Success! Check your inbox.</span>
                </>
              ) : (
                <>
                  <AlertCircle className="w-5 h-5 text-rose-600 shrink-0" />
                  <span>Delivery Diagnostic Error</span>
                </>
              )}
            </div>

            <p className="leading-relaxed pl-7">{testResult.message}</p>

            {testResult.error && (
              <div className="pl-7 pt-1 font-mono text-[11px] text-rose-700 dark:text-rose-300">
                <code>{testResult.error}</code>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};
